from __future__ import annotations

from collections import OrderedDict
from pathlib import Path


def normalize_proc_names(raw_text: str) -> list[str]:
    ordered: OrderedDict[str, None] = OrderedDict()
    for line in raw_text.splitlines():
        name = line.strip()
        if name:
            ordered[name] = None

    if "map_default" not in ordered:
        ordered["map_default"] = None
        ordered.move_to_end("map_default", last=False)

    return list(ordered.keys())


def generate_audiodata_scr(bundle_name: str, raw_proc_text: str, *, load_mode: str = "audio") -> str:
    bank_name = Path(bundle_name.strip()).stem
    if not bank_name:
        raise ValueError("Bundle name is required to generate audiodata.scr.")
    if load_mode not in {"audio", "localised"}:
        raise ValueError("load_mode must be 'audio' or 'localised'.")

    proc_names = normalize_proc_names(raw_proc_text)
    loader_name = "LoadLocalisedAudioBank" if load_mode == "localised" else "LoadAudioBanks"
    lines = [
        '!include("AudioScript.def")',
        "",
        "// Generated by DyingAudio.",
        "// This placeholder loads the selected bank in every listed AudioProc.",
        "",
    ]

    for proc_name in proc_names:
        lines.extend(
            [
                f'AudioProc("{proc_name}")',
                "{",
                f'    {loader_name}("{bank_name}")',
                "}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"
